### ISSUE TITLE
compilation fail in some env since PR #109

### ISSUE THREAD

**Issue by valgit** [slowmoVideo/slowmoVideo#111]
the PR #109 ( Provide TVL1 optical flow algo) create some compilation error in some env (see issue #110 for eg.)
@diehummel provide some hints : 

> 
>
>i was able now to compile it with this changes in flowSourceOpenCV_sV.cpp:
>
>// cv::Ptrcv::DenseOpticalFlow tvl1 = cv::createOptFlow_DualTVL1();
>cv::Ptrcv::DualTVL1OpticalFlow tvl1 = cv::createOptFlow_DualTVL1();
>// tvl1->set("lambda", lambda);
>tvl1->setLambda(lambda);
>// tvl1->set("tau", tau);
>tvl1->setTau(tau);
>//tvl1->set("nscales", nscales);
>tvl1->setScalesNumber(nscales);
>//tvl1->set("warps", warps);
>tvl1->setWarpingsNumber(warps);
>//tvl1->set("iterations", iterations);
>tvl1->setInnerIterations(iterations);
>tvl1->setOuterIterations(iterations);
>//tvl1->set("epsilon", epsilon);

manual of OpenCV 3.1 (http://docs.opencv.org/trunk/dc/d47/classcv_1_1DualTVL1OpticalFlow.html) info said that we need to include : `#include "tracking.hpp"` we need to check for that.

**Comment by diehummel** [comment]
i missed 

tvl1->setEpsilon(epsilon);

on the copy/paste.

**Comment by valgit** [comment]
close by PR #113
