### ISSUE TITLE
Ubuntu 15.10 make fails

### ISSUE THREAD

**Issue by viktorsmari** [slowmoVideo/slowmoVideo#76]
Is it possible to get this working on Ubuntu 15.10?
And improve the instructions if it is possible.

```
[ 66%] Generating ui_aboutDialog.h
Scanning dependencies of target slowmoUI
[ 66%] Building CXX object slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/main.cpp.o
In file included from /home/viktor/test/slowmoVideo/src/slowmoVideo/slowmoUI/mainwindow.h:15:0,
                 from /home/viktor/test/slowmoVideo/src/slowmoVideo/slowmoUI/main.cpp:14:
/home/viktor/test/slowmoVideo/src/slowmoVideo/slowmoUI/frameMonitor.h:39:47: error: expected ‘;’ at end of member declaration
     virtual void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;
                                               ^
/home/viktor/test/slowmoVideo/src/slowmoVideo/slowmoUI/frameMonitor.h:39:49: error: ‘Q_DECL_OVERRIDE’ does not name a type
     virtual void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;
                                                 ^
slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/build.make:234: recipe for target 'slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/main.cpp.o' failed
make[2]: *** [slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:506: recipe for target 'slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/all' failed
make[1]: *** [slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by valgit** [comment]
which Qt version did you use ? seems that Q_DECL_OVERRIDE has been introduce in Qt5.

**Comment by viktorsmari** [comment]
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu

**Comment by valgit** [comment]
@viktorsmari I think we can do a patch/correction easily  but I would use QT5 instead if I where you, it's way better than Qt5

**Comment by viktorsmari** [comment]
I am having additional problems installing QT 5 which takes up additional 1GB of hd space and the installation estimates it will take up to 20 minutes. In my opinion, that is rather a high overhead.

Would be very nice to have it running without that trouble.

**Comment by valgit** [comment]
@viktorsmari I've take a look at the wiki, lot's of info are a bit old but it's a good start ! Thanks for the input.

**Comment by partofthething** [comment]
Just built it fine on 15.10 using the instructions on the wiki. Looks like this can be closed.

**Comment by valgit** [comment]
@partofthething thanks for your input.
