### ISSUE TITLE
slowmoVideo doesn't compile with opencv-4.1.2

### ISSUE THREAD

**Issue by HJarausch** [slowmoVideo/slowmoVideo#164]
There are problems with (e.g.)
src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:264:15: 
error: 'class cv::DenseOpticalFlow' has no member named 'set'
  264 |         tvl1->set("lambda", lambda);

(On Gentoo Linux with opencv-4.1.2 installed)

**Comment by alexmyczko** [comment]
there's a patch for that? https://github.com/slowmoVideo/slowmoVideo/issues/157

**Comment by Granjow** [comment]
Closing as duplicate of #157
