### ISSUE TITLE
Does not compile with opencv 4.0.0

### ISSUE THREAD

**Issue by JackDesBwa** [slowmoVideo/slowmoVideo#157]
I got into troubles when trying to compile slowmoVideo today (hash 32b1902) with opencv 4.0.0
It seems that API changed.

Here are the errors reported by gcc 8.2.1(it also reports lots of deprecated warnings "warning: dynamic exception specifications are deprecated in C++11"):
```
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp: In member function 'virtual FlowField_sV* FlowSourceOpenCV_sV::buildFlow(uint, uint, FrameSize)':
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:161:55: error: 'CV_LOAD_IMAGE_ANYDEPTH' was not declared in this scope
         prevgray = cv::imread(prevpath.toStdString(), CV_LOAD_IMAGE_ANYDEPTH);
                                                       ^~~~~~~~~~~~~~~~~~~~~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:161:55: note: suggested alternative: 'CV_MAT_DEPTH'
         prevgray = cv::imread(prevpath.toStdString(), CV_LOAD_IMAGE_ANYDEPTH);
                                                       ^~~~~~~~~~~~~~~~~~~~~~
                                                       CV_MAT_DEPTH
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp: In member function 'void FlowSourceOpenCV_sV::buildFlowOpenCV_CPU(cv::Mat&, cv::Mat&, std::__cxx11::string)':
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:263:50: error: 'createOptFlow_DualTVL1' is not a member of 'cv'
         cv::Ptr<cv::DenseOpticalFlow> tvl1 = cv::createOptFlow_DualTVL1();
                                                  ^~~~~~~~~~~~~~~~~~~~~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:264:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("lambda", lambda);
               ^~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:265:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("tau", tau);
               ^~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:266:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("nscales", nscales);
               ^~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:267:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("warps", warps);
               ^~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:268:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("iterations", iterations);
               ^~~
/tmp/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:269:15: error: 'class cv::DenseOpticalFlow' has no member named 'set'
         tvl1->set("epsilon", epsilon);
               ^~~
```

And here is my patch to make it compile, but I do not know if it is the best way to correct it:
```patch
diff --git i/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp w/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp
index ae49feb..57ddcce 100644
--- i/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp
+++ w/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp
@@ -260,13 +260,13 @@ void FlowSourceOpenCV_sV::buildFlowOpenCV_CPU(cv::Mat& prevgray, cv::Mat& gray,
     dumpAlgosParams();
     cv::Mat_<cv::Point2f> flow;
     if (algo == 1) { // DualTVL1
-        cv::Ptr<cv::DenseOpticalFlow> tvl1 = cv::createOptFlow_DualTVL1();
-        tvl1->set("lambda", lambda);
-        tvl1->set("tau", tau);
-        tvl1->set("nscales", nscales);
-        tvl1->set("warps", warps);
-        tvl1->set("iterations", iterations);
-        tvl1->set("epsilon", epsilon);
+        cv::Ptr<cv::superres::DualTVL1OpticalFlow> tvl1 = cv::superres::createOptFlow_DualTVL1();
+        tvl1->setLambda(lambda);
+        tvl1->setTau(tau);
+        tvl1->setScalesNumber(nscales);
+        tvl1->setWarpingsNumber(warps);
+        tvl1->setIterations(iterations);
+        tvl1->setEpsilon(epsilon);
         tvl1->calc(prevgray, gray, flow);
     } else { // _FARN_
         // TODO: check to use prev flow as initial flow ? (flags)
diff --git i/src/slowmoVideo/project/flowSourceOpenCV_sV.h w/src/slowmoVideo/project/flowSourceOpenCV_sV.h
index 4f70868..2437769 100644
--- i/src/slowmoVideo/project/flowSourceOpenCV_sV.h
+++ w/src/slowmoVideo/project/flowSourceOpenCV_sV.h
@@ -22,6 +22,8 @@ the Free Software Foundation, either version 3 of the License, or
 #include "opencv2/imgproc/imgproc.hpp"
 #include "opencv2/highgui/highgui.hpp"
 #include "opencv2/opencv_modules.hpp"
+#include "opencv2/superres/optical_flow.hpp"
+#include "opencv2/imgcodecs/legacy/constants_c.h"
 
 #if CV_MAJOR_VERSION == 2
 #include "opencv2/core/gpumat.hpp"
```

**Comment by alexmyczko** [comment]
I would like to know if that patch is good? I've got: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922598

**Comment by JackDesBwa** [comment]
My "do not know if it is the best way to correct it" means "not sure it is the most elegant way".
It works on my Archlinux system. I do not use this software much, but the optical flow created with the DualTVL1 method looks normal. By the way, it is just a one-to-one translation.

**Comment by valgit** [comment]
@JackDesBwa , not tested but in looking at your diff seems good to me
